[package]
name = "ffi-gen-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
ffi-gen = { version = "0.1.0", path = ".." }
proc-macro2 = "1.0.32"
quote = "1.0.10"
syn = "1.0.81"
