on:
  push:
    branches:
    - master
  pull_request:

name: ffi-gen

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install rust toolchain
      uses: hecrj/setup-rust-action@v1
      with:
        channel: nightly

    - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
      with:
        sdk: 2.16.1

    - run: npm i -g prettier
    - run: cargo install --git https://github.com/vmx/wasm-multi-value-reverse-polyfill --locked

    - name: cargo test
      run: cargo test --features test_runner --workspace

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install rust toolchain
      uses: hecrj/setup-rust-action@v1
      with:
        channel: nightly
        components: rustfmt

    - name: cargo fmt
      run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install rust toolchain
      uses: hecrj/setup-rust-action@v1
      with:
        channel: nightly
        components: clippy

    - uses: dart-lang/setup-dart@v1
    - run: npm i -g prettier 

    - name: cargo clippy
      run: cargo clippy --workspace --examples --tests --all-features -- -D warnings
